version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    volumes:
      - /opt/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  sso:
    # build:
    #   context: .
    #   dockerfile: ./pcloud-sso/Dockerfile
    image: calvinchu/pcloud-sso-dockerize
    container_name: sso
    command: bash -c "rm -f tmp/pids/server.pid && dockerize -wait tcp://db:3306 -timeout 1m && bundle exec unicorn -p 3000 -c config/unicorn/production.rb"
    env_file: .env
    volumes:
      - ./pcloud-sso:/home/app/rails-app
      - /tmp/unicorn:/tmp/unicorn
    restart: on-failure
    depends_on:
      - db
      - redis
  portal:
    # build:
    #   context: .
    #   dockerfile: ./pcloud-portal/Dockerfile
    image: calvinchu/pcloud-portal-dockerize
    container_name: portal
    command: bash -c "rm -f tmp/pids/server.pid && dockerize -wait tcp://db:3306 -timeout 1m && bundle exec unicorn -p 3000 -c config/unicorn/production.rb"
    env_file: .env
    volumes:
      - ./pcloud-portal:/home/app/rails-app
      - /tmp/unicorn:/tmp/unicorn
    restart: on-failure
    depends_on:
      - db
      - redis
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile_dev
    # image: nginx-certbot
    container_name: web
    ports:
      - 80:80
      - 443:443
    volumes:
      - /tmp/unicorn:/tmp/unicorn
    #   - /opt/log/nginx:/var/log/nginx
    #   - /opt/nginx/conf.d:/etc/nginx/conf.d
    #   - /opt/letsencrypt:/etc/letsencrypt
    restart: always
    depends_on: 
      - sso
      - portal
    env_file: .env
  mongooseim:
    build:
      context: .
      dockerfile: ./mongooseim/Dockerfile
    container_name: mongooseim
    env_file: .env
    volumes:
      - ./mongooseim/log:/data/log
      - ./mongooseim/mnesia:/data/mnesia
    ports:
      - 5222:5222
      - 5280:5280
      - 5269:5269
      - 4369:4369
      - 9100:9100
    depends_on:
      - db
      - redis

