FROM nginx

ENV LANG C.UTF-8
# 指定時區，否則會用 GMT
ENV TZ Asia/Taipei
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


ENV APP_HOME /home/app/rails-app

WORKDIR $APP_HOME

# create log directory
RUN mkdir -p log/sso log/portal log/dureading log/pcstore

# copy over static assets
COPY nginx/public public/

COPY nginx/sso.lovefunthing.com.conf /tmp/sso.nginx
COPY nginx/portal.lovefunthing.com.conf /tmp/portal.nginx
COPY nginx/dureading.lovefunthing.com.conf /tmp/dureading.nginx
COPY nginx/pcstore.lovefunthing.com.conf /tmp/pcstore.nginx

RUN envsubst '$APP_HOME' < /tmp/sso.nginx > /etc/nginx/conf.d/sso.lovefunthing.com.conf
RUN envsubst '$APP_HOME' < /tmp/portal.nginx > /etc/nginx/conf.d/portal.lovefunthing.com.conf
RUN envsubst '$APP_HOME' < /tmp/dureading.nginx > /etc/nginx/conf.d/dureading.lovefunthing.com.conf
RUN envsubst '$APP_HOME' < /tmp/pcstore.nginx > /etc/nginx/conf.d/pcstore.lovefunthing.com.conf

EXPOSE 80

# CMD [ "service nginx start" ]

# Use the "exec" form of CMD so Nginx shuts down gracefully on SIGTERM (i.e. `docker stop`)
CMD [ "nginx-debug", "-g", "daemon off;" ]